stages:
    - build
    - push
    - deploy

before_script: 
    - docker login registry.gitlab.com -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build_job:
    stage: build
    script:
        - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .

push_job:
    stage: push
    script:
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

deploy_job:
    stage: deploy
    when: manual
    tags:
        - manual-deploy  
    script:
        - docker compose down
        - docker compose pull
        - docker compose up -d
