volumes:
  postgres_data:
    name: postgres_data

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    #depends_on:
      #- db

  #db:
    #image: postgres:14.17
    #environment:
     #DB_HOST: db
      #DB_PORT: 5432
      #DB_NAME: django
      #DB_USER: admin
      #DB_PASSWORD: admin
    #volumes:
      #- postgres_data:/var/lib/postgresql/data/
    #ports:
      #- "5432:5432"