volumes:
  postgres_data:
    name: postgres_data

services:
  web:
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
    build:
      context: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env-file:
      - .env

  db:
    image: postgres:14.17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env-file:
      - .env